package def.jqueryui;
import def.jquery.JQueryEasingFunction;
@jsweet.lang.Interface
@jsweet.lang.Mixin(target=def.jquery.JQueryEasingFunctions.class)
public abstract class JQueryEasingFunctions extends def.jquery.JQueryEasingFunctions {
    public JQueryEasingFunction easeInQuad;
    public JQueryEasingFunction easeOutQuad;
    public JQueryEasingFunction easeInOutQuad;
    public JQueryEasingFunction easeInCubic;
    public JQueryEasingFunction easeOutCubic;
    public JQueryEasingFunction easeInOutCubic;
    public JQueryEasingFunction easeInQuart;
    public JQueryEasingFunction easeOutQuart;
    public JQueryEasingFunction easeInOutQuart;
    public JQueryEasingFunction easeInQuint;
    public JQueryEasingFunction easeOutQuint;
    public JQueryEasingFunction easeInOutQuint;
    public JQueryEasingFunction easeInExpo;
    public JQueryEasingFunction easeOutExpo;
    public JQueryEasingFunction easeInOutExpo;
    public JQueryEasingFunction easeInSine;
    public JQueryEasingFunction easeOutSine;
    public JQueryEasingFunction easeInOutSine;
    public JQueryEasingFunction easeInCirc;
    public JQueryEasingFunction easeOutCirc;
    public JQueryEasingFunction easeInOutCirc;
    public JQueryEasingFunction easeInElastic;
    public JQueryEasingFunction easeOutElastic;
    public JQueryEasingFunction easeInOutElastic;
    public JQueryEasingFunction easeInBack;
    public JQueryEasingFunction easeOutBack;
    public JQueryEasingFunction easeInOutBack;
    public JQueryEasingFunction easeInBounce;
    public JQueryEasingFunction easeOutBounce;
    public JQueryEasingFunction easeInOutBounce;
    native public double easeInQuad(double percent);
    native public double easeOutQuad(double percent);
    native public double easeInOutQuad(double percent);
    native public double easeInCubic(double percent);
    native public double easeOutCubic(double percent);
    native public double easeInOutCubic(double percent);
    native public double easeInQuart(double percent);
    native public double easeOutQuart(double percent);
    native public double easeInOutQuart(double percent);
    native public double easeInQuint(double percent);
    native public double easeOutQuint(double percent);
    native public double easeInOutQuint(double percent);
    native public double easeInExpo(double percent);
    native public double easeOutExpo(double percent);
    native public double easeInOutExpo(double percent);
    native public double easeInSine(double percent);
    native public double easeOutSine(double percent);
    native public double easeInOutSine(double percent);
    native public double easeInCirc(double percent);
    native public double easeOutCirc(double percent);
    native public double easeInOutCirc(double percent);
    native public double easeInElastic(double percent);
    native public double easeOutElastic(double percent);
    native public double easeInOutElastic(double percent);
    native public double easeInBack(double percent);
    native public double easeOutBack(double percent);
    native public double easeInOutBack(double percent);
    native public double easeInBounce(double percent);
    native public double easeOutBounce(double percent);
    native public double easeInOutBounce(double percent);
}

